version: '3.1'
services:
  app:
    container_name: app-springboot-furniture
    image: app-springboot-furniture
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - app-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nextlevel


  pgadmin:
    container_name: pgadmin4_container_furniture
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
volumes:
  app-data:
